### ISSUE TITLE
Add Watir::IE.new_process() support back

### ISSUE THREAD

**Issue by ghost** [watir/watir_meta#9]
The Watir::IE.new_process() has been deprecated but it provides the ability to launch the IE web browser in 'private browsing' mode in addition to enabling the no frame merging option.

This is required when running multiple IE web browsers simultaneously with unique sessions and isolating cookies.

The WIN32OLE InternetExplorer.Application object does not appear to support starting IE in private browsing mode or enabling no frame merging.

Can this support be added again?

**Comment by jarmo** [comment]
This issue belongs to the `watir-classic` repository at https://github.com/watir/watir-classic/issues?state=open

**Comment by jarmo** [comment]
I don't see any code of IE being launched with `-private` switch at all, which implies that it has never been launched in private mode.

Also i've created a more specific issue into watir-classic repository at https://github.com/watir/watir-classic/issues/63

Also, i don't see anything related with `new_process` being deprecated. It is not deprecated. I guess you thought that it is deprecated because `watir` gem did throw you some `NoMethodError`? This will be fixed in next version of  `watir` and `watir-classic`, but as you can see from the opened issue then the `new_process` might not still work. I don't have any good ideas of how to solve it yet either.

**Comment by jarmo** [comment]
Closing this.
